import {
  IconActivity,
  IconApi,
  IconBell,
  IconBroadcast,
  IconGauge,
  IconLogs,
  IconTimeline,
  IconBucket,
  IconCertificate,
  IconCloudNetwork,
  IconCreditCard,
  IconDatabase,
  IconDatabaseSearch,
  IconDatabaseStar,
  IconFingerprint,
  IconIdBadge2,
  IconKey,
  IconBrain,
  IconCpu,
  IconLockAccess,
  IconScale,
  IconServer,
  IconLambda,
  IconShieldCheck,
  IconSitemap,
  IconStack,
  IconTopologyFull,
  IconWall,
  IconWaveSine,
  IconWorld,
  IconAlignBoxCenterMiddle,
  IconLicense,
  IconAppWindow,
  IconFiles,
  IconContainer,
  IconHexagon,
} from '@tabler/icons-react';

export type NodeDef = {
  id: string;
  label: string;
  category: Category;
  Icon: React.ComponentType<{ color?: string; strokeWidth?: number }>;
  /** When set, dragging an edge from this node defaults to this edge type. */
  defaultEdgeType?: 'applies' | 'hosts';
  /** Controls alternate visual rendering for pre-placed context nodes. */
  variant?: 'application' | 'data';
};

export const CATEGORIES = [
  'Input',
  'Compute',
  'Storage',
  'Network',
  'Security',
  'Messaging',
  'Observability',
] as const;
export type Category = (typeof CATEGORIES)[number];

export const NODE_REGISTRY: Record<string, NodeDef> = {
  internet: {
    id: 'internet',
    label: 'Internet',
    category: 'Input',
    Icon: IconWorld,
  },
  application: {
    id: 'application',
    label: 'Application',
    category: 'Input',
    Icon: IconAppWindow,
    variant: 'application',
    defaultEdgeType: 'hosts',
  },
  static_assets: {
    id: 'static_assets',
    label: 'Static Assets',
    category: 'Input',
    Icon: IconFiles,
    variant: 'data',
  },
  compute: {
    id: 'compute',
    label: 'Server',
    category: 'Compute',
    Icon: IconServer,
  },
  serverless: {
    id: 'serverless',
    label: 'Serverless Function',
    category: 'Compute',
    Icon: IconLambda,
  },
  object_storage: {
    id: 'object_storage',
    label: 'Object Storage',
    category: 'Storage',
    Icon: IconBucket,
  },
  database: {
    id: 'database',
    label: 'Relational Database',
    category: 'Storage',
    Icon: IconDatabase,
  },
  cache: { id: 'cache', label: 'Cache', category: 'Storage', Icon: IconStack },
  cdn: { id: 'cdn', label: 'CDN', category: 'Network', Icon: IconCloudNetwork },
  dns: { id: 'dns', label: 'DNS', category: 'Network', Icon: IconLicense },
  load_balancer: {
    id: 'load_balancer',
    label: 'Load Balancer',
    category: 'Network',
    Icon: IconScale,
  },
  api_gateway: {
    id: 'api_gateway',
    label: 'API Gateway',
    category: 'Network',
    Icon: IconApi,
  },
  private_network: {
    id: 'private_network',
    label: 'Private Network',
    category: 'Network',
    Icon: IconTopologyFull,
  },
  certificate: {
    id: 'certificate',
    label: 'Certificate',
    category: 'Security',
    Icon: IconCertificate,
    defaultEdgeType: 'applies',
  },
  waf: {
    id: 'waf',
    label: 'WAF',
    category: 'Security',
    Icon: IconShieldCheck,
    defaultEdgeType: 'applies',
  },
  queue: {
    id: 'queue',
    label: 'Queue',
    category: 'Messaging',
    Icon: IconAlignBoxCenterMiddle,
  },
  auth: {
    id: 'auth',
    label: 'Auth Service',
    category: 'Security',
    Icon: IconFingerprint,
    defaultEdgeType: 'applies',
  },
  secrets_manager: {
    id: 'secrets_manager',
    label: 'Secrets Manager',
    category: 'Security',
    Icon: IconKey,
  },
  payment_processor: {
    id: 'payment_processor',
    label: 'Payment Processor',
    category: 'Input',
    Icon: IconCreditCard,
  },
  nosql_database: {
    id: 'nosql_database',
    label: 'NoSQL Database',
    category: 'Storage',
    Icon: IconDatabaseStar,
  },
  search: {
    id: 'search',
    label: 'Search',
    category: 'Storage',
    Icon: IconDatabaseSearch,
  },
  streaming: {
    id: 'streaming',
    label: 'Data Stream',
    category: 'Messaging',
    Icon: IconWaveSine,
  },
  event_bus: {
    id: 'event_bus',
    label: 'Event Bus',
    category: 'Messaging',
    Icon: IconBroadcast,
  },
  vpn: {
    id: 'vpn',
    label: 'VPN',
    category: 'Network',
    Icon: IconLockAccess,
  },
  firewall: {
    id: 'firewall',
    label: 'Firewall',
    category: 'Security',
    Icon: IconWall,
    defaultEdgeType: 'applies',
  },
  identity_provider: {
    id: 'identity_provider',
    label: 'Identity Provider',
    category: 'Security',
    Icon: IconIdBadge2,
    defaultEdgeType: 'applies',
  },
  monitoring: {
    id: 'monitoring',
    label: 'Monitoring',
    category: 'Observability',
    Icon: IconActivity,
    defaultEdgeType: 'applies',
  },
  log_aggregator: {
    id: 'log_aggregator',
    label: 'Log Aggregator',
    category: 'Observability',
    Icon: IconLogs,
  },
  tracing: {
    id: 'tracing',
    label: 'Distributed Tracing',
    category: 'Observability',
    Icon: IconTimeline,
  },
  metrics: {
    id: 'metrics',
    label: 'Metrics Store',
    category: 'Observability',
    Icon: IconGauge,
  },
  alerting: {
    id: 'alerting',
    label: 'Alerting',
    category: 'Observability',
    Icon: IconBell,
  },
  container: {
    id: 'container',
    label: 'Container',
    category: 'Compute',
    Icon: IconContainer,
  },
  kubernetes: {
    id: 'kubernetes',
    label: 'Kubernetes',
    category: 'Compute',
    Icon: IconHexagon,
  },
  orchestrator: {
    id: 'orchestrator',
    label: 'Orchestrator',
    category: 'Compute',
    Icon: IconSitemap,
  },
  foundation_model: {
    id: 'foundation_model',
    label: 'Foundation Model',
    category: 'Compute',
    Icon: IconBrain,
  },
  ml_platform: {
    id: 'ml_platform',
    label: 'ML Platform',
    category: 'Compute',
    Icon: IconCpu,
  },
};
