import {
  IconActivity,
  IconApi,
  IconBell,
  IconBroadcast,
  IconGauge,
  IconLogs,
  IconTimeline,
  IconBucket,
  IconCloudNetwork,
  IconCreditCard,
  IconDatabase,
  IconDatabaseSearch,
  IconDatabaseStar,
  IconFingerprint,
  IconIdBadge2,
  IconKey,
  IconBrain,
  IconCpu,
  IconLockAccess,
  IconScale,
  IconServer,
  IconLambda,
  IconShieldCheck,
  IconSitemap,
  IconStack,
  IconTopologyFull,
  IconWall,
  IconWaveSine,
  IconWorld,
  IconAlignBoxCenterMiddle,
  IconLicense,
  IconAppWindow,
  IconFiles,
  IconContainer,
  IconHexagon,
} from '@tabler/icons-react';
import type { TradeoffProfile } from '@arcantect/scorer';

export type NodeDef = {
  id: string;
  label: string;
  category: Category;
  Icon: React.ComponentType<{ color?: string; strokeWidth?: number }>;
  /** When set, dragging an edge from this node defaults to this edge type. */
  defaultEdgeType?: 'applies' | 'hosts';
  /** Controls alternate visual rendering for pre-placed context nodes. */
  variant?: 'application' | 'data';
  /** Functional capabilities this rune can satisfy in capability-goal rules. */
  capabilities?: string[];
  /** Signed deltas contributed to the solution's tradeoff profile when this rune is placed. */
  tradeoffs?: Partial<TradeoffProfile>;
};

export const CATEGORIES = [
  'Input',
  'Compute',
  'Storage',
  'Network',
  'Security',
  'Messaging',
  'Observability',
] as const;
export type Category = (typeof CATEGORIES)[number];

export const NODE_REGISTRY: Record<string, NodeDef> = {
  internet: {
    id: 'internet',
    label: 'Internet',
    category: 'Input',
    Icon: IconWorld,
    capabilities: ['public-ingress'],
    tradeoffs: {},
  },
  application: {
    id: 'application',
    label: 'Application',
    category: 'Input',
    Icon: IconAppWindow,
    variant: 'application',
    defaultEdgeType: 'hosts',
    capabilities: ['hosted-app'],
    tradeoffs: { complexity: 2 },
  },
  static_assets: {
    id: 'static_assets',
    label: 'Static Assets',
    category: 'Input',
    Icon: IconFiles,
    variant: 'data',
    capabilities: ['static-origin'],
    tradeoffs: { cost: -1 },
  },
  compute: {
    id: 'compute',
    label: 'Server',
    category: 'Compute',
    Icon: IconServer,
    capabilities: ['compute-layer', 'static-origin'],
    tradeoffs: { latency: -1, cost: -2, operability: -1, complexity: 1 },
  },
  serverless: {
    id: 'serverless',
    label: 'Serverless Function',
    category: 'Compute',
    Icon: IconLambda,
    capabilities: ['compute-layer'],
    tradeoffs: { latency: -1, cost: 1, operability: 1, complexity: -1 },
  },
  object_storage: {
    id: 'object_storage',
    label: 'Object Storage',
    category: 'Storage',
    Icon: IconBucket,
    capabilities: ['static-origin'],
    tradeoffs: { cost: 1, operability: 2, latency: 1 },
  },
  database: {
    id: 'database',
    label: 'Relational Database',
    category: 'Storage',
    Icon: IconDatabase,
    capabilities: ['data-persistence', 'transactional'],
    tradeoffs: { consistency: 2, cost: -1, operability: -1 },
  },
  cache: {
    id: 'cache',
    label: 'Cache',
    category: 'Storage',
    Icon: IconStack,
    capabilities: ['cache-layer'],
    tradeoffs: { latency: 2, cost: -1, complexity: -1 },
  },
  cdn: {
    id: 'cdn',
    label: 'CDN',
    category: 'Network',
    Icon: IconCloudNetwork,
    capabilities: ['edge-delivery', 'threat-filter'],
    tradeoffs: { latency: 2, cost: -1, throughput: 2 },
  },
  dns: {
    id: 'dns',
    label: 'DNS',
    category: 'Network',
    Icon: IconLicense,
    capabilities: ['dns-resolution'],
    tradeoffs: { operability: 1 },
  },
  load_balancer: {
    id: 'load_balancer',
    label: 'Load Balancer',
    category: 'Network',
    Icon: IconScale,
    capabilities: ['traffic-distribution'],
    tradeoffs: { throughput: 2, operability: -1, complexity: -1 },
  },
  api_gateway: {
    id: 'api_gateway',
    label: 'API Gateway',
    category: 'Network',
    Icon: IconApi,
    capabilities: ['auth-boundary', 'rate-limiter', 'request-router'],
    tradeoffs: { security: 1, operability: 1, cost: -1 },
  },
  private_network: {
    id: 'private_network',
    label: 'Private Network',
    category: 'Network',
    Icon: IconTopologyFull,
    capabilities: [],
    tradeoffs: {},
  },
  waf: {
    id: 'waf',
    label: 'WAF',
    category: 'Security',
    Icon: IconShieldCheck,
    defaultEdgeType: 'applies',
    capabilities: ['threat-filter', 'rate-limiter'],
    tradeoffs: { security: 2, cost: -2, complexity: -1 },
  },
  queue: {
    id: 'queue',
    label: 'Queue',
    category: 'Messaging',
    Icon: IconAlignBoxCenterMiddle,
    capabilities: ['async-decoupler', 'durable-messaging'],
    tradeoffs: { throughput: 2, blastRadius: 1, complexity: -1, latency: -1 },
  },
  auth: {
    id: 'auth',
    label: 'Auth Service',
    category: 'Security',
    Icon: IconFingerprint,
    defaultEdgeType: 'applies',
    capabilities: ['auth-boundary', 'identity-verification'],
    tradeoffs: { security: 2, complexity: -1 },
  },
  secrets_manager: {
    id: 'secrets_manager',
    label: 'Secrets Manager',
    category: 'Security',
    Icon: IconKey,
    capabilities: ['secrets-store'],
    tradeoffs: { security: 2, operability: 1, cost: -1 },
  },
  payment_processor: {
    id: 'payment_processor',
    label: 'Payment Processor',
    category: 'Input',
    Icon: IconCreditCard,
    capabilities: ['payment-processing'],
    tradeoffs: {},
  },
  nosql_database: {
    id: 'nosql_database',
    label: 'NoSQL Database',
    category: 'Storage',
    Icon: IconDatabaseStar,
    capabilities: ['data-persistence'],
    tradeoffs: { throughput: 1, consistency: -1, cost: 1 },
  },
  search: {
    id: 'search',
    label: 'Search',
    category: 'Storage',
    Icon: IconDatabaseSearch,
    capabilities: ['data-persistence'],
    tradeoffs: { latency: 1, cost: -1 },
  },
  streaming: {
    id: 'streaming',
    label: 'Data Stream',
    category: 'Messaging',
    Icon: IconWaveSine,
    capabilities: ['async-decoupler', 'high-throughput-stream'],
    tradeoffs: { throughput: 3, cost: -2, complexity: -2 },
  },
  event_bus: {
    id: 'event_bus',
    label: 'Event Bus',
    category: 'Messaging',
    Icon: IconBroadcast,
    capabilities: ['async-decoupler', 'event-routing'],
    tradeoffs: { throughput: 1, complexity: -2 },
  },
  vpn: {
    id: 'vpn',
    label: 'VPN',
    category: 'Network',
    Icon: IconLockAccess,
    capabilities: ['network-isolation'],
    tradeoffs: { security: 1, operability: -1 },
  },
  firewall: {
    id: 'firewall',
    label: 'Firewall',
    category: 'Security',
    Icon: IconWall,
    defaultEdgeType: 'applies',
    capabilities: ['threat-filter', 'network-isolation'],
    tradeoffs: { security: 2, operability: -1 },
  },
  identity_provider: {
    id: 'identity_provider',
    label: 'Identity Provider',
    category: 'Security',
    Icon: IconIdBadge2,
    defaultEdgeType: 'applies',
    capabilities: ['auth-boundary', 'identity-verification'],
    tradeoffs: { security: 2, operability: 1, cost: -1 },
  },
  monitoring: {
    id: 'monitoring',
    label: 'Monitoring',
    category: 'Observability',
    Icon: IconActivity,
    defaultEdgeType: 'applies',
    capabilities: ['observability'],
    tradeoffs: { operability: 2 },
  },
  log_aggregator: {
    id: 'log_aggregator',
    label: 'Log Aggregator',
    category: 'Observability',
    Icon: IconLogs,
    capabilities: ['observability'],
    tradeoffs: { operability: 1 },
  },
  tracing: {
    id: 'tracing',
    label: 'Distributed Tracing',
    category: 'Observability',
    Icon: IconTimeline,
    capabilities: ['observability'],
    tradeoffs: { operability: 2, complexity: -1 },
  },
  metrics: {
    id: 'metrics',
    label: 'Metrics Store',
    category: 'Observability',
    Icon: IconGauge,
    capabilities: ['observability'],
    tradeoffs: { operability: 1 },
  },
  alerting: {
    id: 'alerting',
    label: 'Alerting',
    category: 'Observability',
    Icon: IconBell,
    capabilities: ['observability'],
    tradeoffs: { operability: 1 },
  },
  container: {
    id: 'container',
    label: 'Container',
    category: 'Compute',
    Icon: IconContainer,
    capabilities: ['compute-layer'],
    tradeoffs: { operability: -1, complexity: -1 },
  },
  kubernetes: {
    id: 'kubernetes',
    label: 'Kubernetes',
    category: 'Compute',
    Icon: IconHexagon,
    capabilities: ['compute-layer', 'traffic-distribution'],
    tradeoffs: { throughput: 2, operability: -3, complexity: -3 },
  },
  orchestrator: {
    id: 'orchestrator',
    label: 'Orchestrator',
    category: 'Compute',
    Icon: IconSitemap,
    capabilities: ['compute-layer'],
    tradeoffs: { operability: -2, complexity: -2 },
  },
  foundation_model: {
    id: 'foundation_model',
    label: 'Foundation Model',
    category: 'Compute',
    Icon: IconBrain,
    capabilities: ['ml-inference'],
    tradeoffs: { cost: -3, latency: -2 },
  },
  ml_platform: {
    id: 'ml_platform',
    label: 'ML Platform',
    category: 'Compute',
    Icon: IconCpu,
    capabilities: ['ml-inference'],
    tradeoffs: { cost: -2, operability: -2 },
  },
};
